package handler

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

// validateAdminToken checks an HMAC-SHA256 token generated by admin-login.go
// Token format: "jemarko:<unixTimestamp>.<hmac-sha256-hex>"
func validateAdminToken(token string, secret string) bool {
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 {
		return false
	}
	payload := parts[0]
	sig := parts[1]

	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(payload))
	expectedSig := hex.EncodeToString(mac.Sum(nil))

	if !hmac.Equal([]byte(sig), []byte(expectedSig)) {
		return false
	}

	// payload is "username:timestamp" — check expiry (8 hours)
	payloadParts := strings.SplitN(payload, ":", 2)
	if len(payloadParts) != 2 {
		return false
	}
	ts, err := strconv.ParseInt(payloadParts[1], 10, 64)
	if err != nil {
		return false
	}
	return time.Since(time.Unix(ts, 0)) <= 8*time.Hour
}

// DashboardGuestMember represents a single invited guest and their RSVP status
type DashboardGuestMember struct {
	Name       string `json:"name"`
	RSVPStatus string `json:"rsvpStatus"` // "attending", "not_attending", "no_response"
	Verified   bool   `json:"verified"`
}

// DashboardGuestGroup represents a family/household group from the invite list
type DashboardGuestGroup struct {
	Address string                 `json:"address"`
	Members []DashboardGuestMember `json:"members"`
}

// DashboardDietaryEntry represents a single dietary requirement submission
type DashboardDietaryEntry struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Diet     string `json:"diet"`
	Verified bool   `json:"verified"`
}

// DashboardUnverifiedRSVP represents an RSVP from someone not on the invite list
type DashboardUnverifiedRSVP struct {
	Name            string   `json:"name"`
	Email           string   `json:"email"`
	IsAttending     bool     `json:"isAttending"`
	AttendingGuests []string `json:"attendingGuests"`
	Diet            string   `json:"diet"`
	SubmittedAt     string   `json:"submittedAt"`
}

// DashboardStats represents summary statistics
type DashboardStats struct {
	TotalInvited    int `json:"totalInvited"`
	TotalRSVPd      int `json:"totalRSVPd"`
	Attending       int `json:"attending"`
	NotAttending    int `json:"notAttending"`
	NoResponse      int `json:"noResponse"`
	WithDietary     int `json:"withDietary"`
	UnverifiedCount int `json:"unverifiedCount"`
}

// DashboardResponse is the full admin dashboard payload
type DashboardResponse struct {
	Success             bool                      `json:"success"`
	Stats               DashboardStats            `json:"stats"`
	GuestGroups         []DashboardGuestGroup     `json:"guestGroups"`
	DietaryRequirements []DashboardDietaryEntry   `json:"dietaryRequirements"`
	UnverifiedRSVPs     []DashboardUnverifiedRSVP `json:"unverifiedRSVPs"`
}

// supabaseGuest matches the DB guests table row
type supabaseGuest struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

// supabaseRSVP matches the DB rsvps table row
type supabaseRSVP struct {
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	Email           string   `json:"email"`
	IsAttending     bool     `json:"is_attending"`
	AttendingGuests []string `json:"attending_guests"`
	Diet            string   `json:"diet"`
	SubmittedAt     string   `json:"submitted_at"`
	Verified        bool     `json:"verified"`
}

// Handler handles admin dashboard data requests
func Handler(w http.ResponseWriter, r *http.Request) {
	setCORSHeaders(w, r)

	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}

	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// --- Auth: validate Bearer token ---
	adminPassword := os.Getenv("ADMIN_PASSWORD")
	if adminPassword == "" {
		log.Printf("ADMIN_PASSWORD env var not configured")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]interface{}{"success": false, "message": "Server configuration error"})
		return
	}

	authHeader := r.Header.Get("Authorization")
	token := strings.TrimPrefix(authHeader, "Bearer ")
	if token == "" || !validateAdminToken(token, adminPassword) {
		log.Printf("Unauthorized admin dashboard access attempt")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]interface{}{"success": false, "message": "Unauthorized"})
		return
	}

	supabaseURL := os.Getenv("SUPABASE_URL")
	supabaseAPIKey := os.Getenv("SUPABASE_API_KEY")

	if supabaseURL == "" || supabaseAPIKey == "" {
		log.Printf("Supabase not configured")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]interface{}{"success": false, "message": "Database not configured"})
		return
	}

	guests, err := fetchGuests(supabaseURL, supabaseAPIKey)
	if err != nil {
		log.Printf("Error fetching guests: %v", err)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]interface{}{"success": false, "message": "Failed to fetch guest list"})
		return
	}

	rsvps, err := fetchRSVPs(supabaseURL, supabaseAPIKey)
	if err != nil {
		log.Printf("Error fetching RSVPs: %v", err)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]interface{}{"success": false, "message": "Failed to fetch RSVPs"})
		return
	}

	resp := buildDashboard(guests, rsvps)
	log.Printf("Admin dashboard: %d invited, %d attending, %d not attending, %d no response, %d dietary, %d unverified",
		resp.Stats.TotalInvited, resp.Stats.Attending, resp.Stats.NotAttending,
		resp.Stats.NoResponse, resp.Stats.WithDietary, resp.Stats.UnverifiedCount)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

// buildDashboard constructs the full dashboard response from raw DB data
func buildDashboard(guests []supabaseGuest, rsvps []supabaseRSVP) DashboardResponse {
	type rsvpResult struct {
		attending bool
		verified  bool
	}

	guestRSVPMap := make(map[string]rsvpResult)
	var dietaryEntries []DashboardDietaryEntry
	var unverifiedRSVPs []DashboardUnverifiedRSVP

	for _, rsvp := range rsvps {
		if !rsvp.Verified {
			unverifiedRSVPs = append(unverifiedRSVPs, DashboardUnverifiedRSVP{
				Name: rsvp.Name, Email: rsvp.Email, IsAttending: rsvp.IsAttending,
				AttendingGuests: rsvp.AttendingGuests, Diet: rsvp.Diet, SubmittedAt: rsvp.SubmittedAt,
			})
			continue
		}
		if rsvp.IsAttending {
			for _, gName := range rsvp.AttendingGuests {
				guestRSVPMap[normaliseName(gName)] = rsvpResult{attending: true, verified: true}
			}
		} else {
			guestRSVPMap[normaliseName(rsvp.Name)] = rsvpResult{attending: false, verified: true}
		}
		if strings.TrimSpace(rsvp.Diet) != "" {
			dietaryEntries = append(dietaryEntries, DashboardDietaryEntry{
				Name: rsvp.Name, Email: rsvp.Email, Diet: rsvp.Diet, Verified: rsvp.Verified,
			})
		}
	}

	guestAddrMap := make(map[string]string)
	for _, g := range guests {
		guestAddrMap[normaliseName(g.Name)] = normalisedAddrKey(g)
	}

	addressRSVPMap := make(map[string][]supabaseRSVP)
	for _, rsvp := range rsvps {
		if rsvp.Verified {
			addRSVPToAddressMap(addressRSVPMap, guestAddrMap, rsvp)
		}
	}

	groupMap := make(map[string][]supabaseGuest)
	groupOrder := []string{}
	for _, g := range guests {
		key := normalisedAddrKey(g)
		if _, exists := groupMap[key]; !exists {
			groupOrder = append(groupOrder, key)
		}
		groupMap[key] = append(groupMap[key], g)
	}

	var guestGroups []DashboardGuestGroup
	totalInvited, attending, notAttending, noResponse := 0, 0, 0, 0

	for _, addrKey := range groupOrder {
		members := groupMap[addrKey]
		householdRSVPs := addressRSVPMap[addrKey]
		displayAddress := ""
		if len(members) > 0 && !strings.HasPrefix(addrKey, "__individual__") {
			displayAddress = strings.TrimSpace(members[0].Address)
		}

		var groupMembers []DashboardGuestMember
		for _, g := range members {
			totalInvited++
			key := normaliseName(g.Name)
			status, verified := "no_response", false

			if res, found := guestRSVPMap[key]; found {
				verified = res.verified
				if res.attending {
					status = "attending"
					attending++
				} else {
					status = "not_attending"
					notAttending++
				}
			} else if len(householdRSVPs) > 0 {
				listedAsAttending := false
				for _, rsvp := range householdRSVPs {
					if rsvp.IsAttending {
						for _, ag := range rsvp.AttendingGuests {
							if normaliseName(ag) == key {
								listedAsAttending = true
								break
							}
						}
					}
				}
				verified = true
				if listedAsAttending {
					status = "attending"
					attending++
				} else {
					status = "not_attending"
					notAttending++
				}
			} else {
				noResponse++
			}

			groupMembers = append(groupMembers, DashboardGuestMember{
				Name: g.Name, RSVPStatus: status, Verified: verified,
			})
		}
		guestGroups = append(guestGroups, DashboardGuestGroup{Address: displayAddress, Members: groupMembers})
	}

	return DashboardResponse{
		Success: true,
		Stats: DashboardStats{
			TotalInvited: totalInvited, TotalRSVPd: attending + notAttending,
			Attending: attending, NotAttending: notAttending, NoResponse: noResponse,
			WithDietary: len(dietaryEntries), UnverifiedCount: len(unverifiedRSVPs),
		},
		GuestGroups: guestGroups, DietaryRequirements: dietaryEntries, UnverifiedRSVPs: unverifiedRSVPs,
	}
}

// normalisedAddrKey returns a stable, unique map key for a guest's address
func normalisedAddrKey(g supabaseGuest) string {
	addr := strings.TrimSpace(g.Address)
	norm := strings.ToLower(addr)
	if addr == "" || norm == "n/a" || norm == "na" || norm == "n.a." || norm == "n.a" {
		return "__individual__:" + g.ID
	}
	return norm
}

// addRSVPToAddressMap assigns an RSVP to its household bucket(s) in addressRSVPMap
func addRSVPToAddressMap(addressRSVPMap map[string][]supabaseRSVP, guestAddrMap map[string]string, rsvp supabaseRSVP) {
	addUnique := func(key string) {
		for _, existing := range addressRSVPMap[key] {
			if existing.ID == rsvp.ID {
				return
			}
		}
		addressRSVPMap[key] = append(addressRSVPMap[key], rsvp)
	}
	if addrKey, ok := guestAddrMap[normaliseName(rsvp.Name)]; ok {
		addUnique(addrKey)
	}
	if rsvp.IsAttending {
		for _, gName := range rsvp.AttendingGuests {
			if addrKey, ok := guestAddrMap[normaliseName(gName)]; ok {
				addUnique(addrKey)
			}
		}
	}
}

// fetchGuests fetches all guests from Supabase
func fetchGuests(supabaseURL, apiKey string) ([]supabaseGuest, error) {
	url := fmt.Sprintf("%s/rest/v1/guests?select=id,name,address&order=address.asc,name.asc", supabaseURL)
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("apikey", apiKey)
	req.Header.Set("Authorization", "Bearer "+apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("supabase returned status %d", resp.StatusCode)
	}
	var guests []supabaseGuest
	if err := json.NewDecoder(resp.Body).Decode(&guests); err != nil {
		return nil, err
	}
	return guests, nil
}

// fetchRSVPs fetches all RSVP submissions from Supabase
func fetchRSVPs(supabaseURL, apiKey string) ([]supabaseRSVP, error) {
	url := fmt.Sprintf("%s/rest/v1/rsvps?select=id,name,email,is_attending,attending_guests,diet,submitted_at,verified&order=submitted_at.desc", supabaseURL)
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("apikey", apiKey)
	req.Header.Set("Authorization", "Bearer "+apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("supabase returned status %d", resp.StatusCode)
	}
	var rsvps []supabaseRSVP
	if err := json.NewDecoder(resp.Body).Decode(&rsvps); err != nil {
		return nil, err
	}
	return rsvps, nil
}

// normaliseName lowercases and trims a name for comparison
func normaliseName(s string) string {
	return strings.ToLower(strings.TrimSpace(s))
}

// setCORSHeaders sets CORS headers for cross-origin requests
func setCORSHeaders(w http.ResponseWriter, r *http.Request) {
	origin := r.Header.Get("Origin")
	if origin == "" {
		origin = "*"
	}
	w.Header().Set("Access-Control-Allow-Origin", origin)
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
	w.Header().Set("Access-Control-Allow-Credentials", "true")
}

